### ISSUE TITLE
enhancement: readability of pillar texts and silhouette

### ISSUE THREAD

**Issue by OlafHaag** [OpenScienceInitiativeUniversityMarburg/OpenScienceInitiativeUniversityMarburg.github.io#5]
As discussed in the slack channel:
The text contained in the pillars is hard to read due to visual noise in the background.
Solution: Blur the background image behind the pillars.

The city silhouette is pixelated and blurry.
Solution: Vectorize the artwork.

So it would more look like this:
![osium-bg-update](https://user-images.githubusercontent.com/4630661/36553580-f9ac787e-17fc-11e8-9812-981c9819f309.jpg)

I have Inkscape/Gimp files for this.

**Comment by PeerHerholz** [comment]
Thank you for working on this valid points. 
If you provide the respective files, @vogelbac and I will change it tomorrow.

**Comment by OlafHaag** [comment]
#7 is providing files to fix this issue.
